/*
SDL scancode to keyboard scancode
*/
u8 in_al_60h[41]=
{
/* SCANCODE_KEY_A     */ 0x1E,
/* SCANCODE_KEY_B     */ 0x30,
/* SCANCODE_KEY_C     */ 0x2E,
/* SCANCODE_KEY_D     */ 0x20,
/* SCANCODE_KEY_E     */ 0x12,
/* SCANCODE_KEY_F     */ 0x21,
/* SCANCODE_KEY_G     */ 0x22,
/* SCANCODE_KEY_H     */ 0x23,
/* SCANCODE_KEY_I     */ 0x17,
/* SCANCODE_KEY_J     */ 0x24,
/* SCANCODE_KEY_K     */ 0x25,
/* SCANCODE_KEY_L     */ 0x26,
/* SCANCODE_KEY_M     */ 0x32,
/* SCANCODE_KEY_N     */ 0x31,
/* SCANCODE_KEY_O     */ 0x18,
/* SCANCODE_KEY_P     */ 0x19,
/* SCANCODE_KEY_Q     */ 0x10,
/* SCANCODE_KEY_R     */ 0x13,
/* SCANCODE_KEY_S     */ 0x1F,
/* SCANCODE_KEY_T     */ 0x14,
/* SCANCODE_KEY_U     */ 0x16,
/* SCANCODE_KEY_V     */ 0x2F,
/* SCANCODE_KEY_W     */ 0x11,
/* SCANCODE_KEY_X     */ 0x2D,
/* SCANCODE_KEY_Y     */ 0x15,
/* SCANCODE_KEY_Z     */ 0x2C,

/* SCANCODE_KEY_1     */ 0x02,
/* SCANCODE_KEY_2     */ 0x03,
/* SCANCODE_KEY_3     */ 0x04,
/* SCANCODE_KEY_4     */ 0x05,
/* SCANCODE_KEY_5     */ 0x06,
/* SCANCODE_KEY_6     */ 0x07,
/* SCANCODE_KEY_7     */ 0x08,
/* SCANCODE_KEY_8     */ 0x09,
/* SCANCODE_KEY_9     */ 0x0A,
/* SCANCODE_KEY_0     */ 0x0B,

/* SCANCODE_RETURN    */ 0x1C,
/* SCANCODE_ESCAPE    */ 0x01,
/* SCANCODE_BACKSPACE */ 0x0E,
/* SCANCODE_TAB       */ 0x0F,
/* SCANCODE_SPACE     */ 0x39,
};
